import type { Page } from '@playwright/test'

const systems = [
  {
    _id: 1,
    ai_register_id: 'AI-001',
    name_ai_system_en: 'Benefits modernization assistant',
    name_ai_system_fr: 'Assistant de modernisation des prestations',
    government_organization: 'Employment and Social Development Canada / Emploi et Développement social Canada',
    description_ai_system_en: 'Supports triage of benefits inquiries using rules-based automation.',
    description_ai_system_fr: 'Soutient le triage des demandes de prestations à l’aide d’une automatisation fondée sur des règles.',
    ai_system_primary_users_en: 'Program officers',
    ai_system_primary_users_fr: 'Agents de programme',
    developed_by_en: 'Government of Canada',
    developed_by_fr: 'Gouvernement du Canada',
    vendor_information: '',
    ai_system_status_en: 'In production',
    ai_system_status_fr: 'En production',
    status_date: '2025-02-01',
    ai_system_capabilities_en: 'Classification and workflow routing',
    ai_system_capabilities_fr: 'Classification et aiguillage du flux de travail',
    data_sources_en: 'Internal program data',
    data_sources_fr: 'Données internes du programme',
    involves_personal_information: 'Y',
    personal_information_banks_en: 'Program records',
    personal_information_banks_fr: 'Dossiers du programme',
    notification_ai: 'Y',
    ai_system_results_en: 'Faster routing for service requests',
    ai_system_results_fr: 'Acheminement plus rapide des demandes de service',
  },
  {
    _id: 2,
    ai_register_id: 'AI-002',
    name_ai_system_en: 'Microsoft translation workflow',
    name_ai_system_fr: 'Flux de traduction Microsoft',
    government_organization: 'Statistics Canada / Statistique Canada',
    description_ai_system_en: 'Uses Microsoft services to support translation workflow review.',
    description_ai_system_fr: 'Utilise les services Microsoft pour soutenir l’examen du flux de traduction.',
    ai_system_primary_users_en: 'Analysts',
    ai_system_primary_users_fr: 'Analystes',
    developed_by_en: 'Vendor',
    developed_by_fr: 'Fournisseur',
    vendor_information: 'Microsoft',
    ai_system_status_en: 'In development',
    ai_system_status_fr: 'En développement',
    status_date: '2024-09-20',
    ai_system_capabilities_en: 'Translation assistance',
    ai_system_capabilities_fr: 'Aide à la traduction',
    data_sources_en: 'Public documents',
    data_sources_fr: 'Documents publics',
    involves_personal_information: 'N',
    personal_information_banks_en: '',
    personal_information_banks_fr: '',
    notification_ai: 'N',
    ai_system_results_en: 'Improved translation workflow consistency',
    ai_system_results_fr: 'Cohérence améliorée du flux de traduction',
  },
  {
    _id: 3,
    ai_register_id: 'AI-003',
    name_ai_system_en: 'Legacy risk model',
    name_ai_system_fr: 'Modèle de risque patrimonial',
    government_organization: 'Transport Canada / Transports Canada',
    description_ai_system_en: 'Retired model formerly used to prioritize inspection planning.',
    description_ai_system_fr: 'Modèle retiré auparavant utilisé pour prioriser la planification des inspections.',
    ai_system_primary_users_en: 'Inspectors',
    ai_system_primary_users_fr: 'Inspecteurs',
    developed_by_en: 'Other',
    developed_by_fr: 'Autre',
    vendor_information: 'Internal prototype',
    ai_system_status_en: 'Retired',
    ai_system_status_fr: 'Retiré',
    status_date: '2023-01-15',
    ai_system_capabilities_en: 'Risk scoring',
    ai_system_capabilities_fr: 'Notation du risque',
    data_sources_en: 'Historical inspection data',
    data_sources_fr: 'Données historiques d’inspection',
    involves_personal_information: 'N',
    personal_information_banks_en: '',
    personal_information_banks_fr: '',
    notification_ai: 'N',
    ai_system_results_en: 'Retired after program review',
    ai_system_results_fr: 'Retiré après examen du programme',
  },
]

export async function stubSystemsApi(page: Page) {
  await page.route('**/api/systems', async (route) => {
    await route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify({
        records: systems,
        total: systems.length,
        lastModified: '2026-04-28T20:10:07.759825',
      }),
    })
  })
}
